redirects:
  getting-started/overview: README.md
  getting-started/git-sync: getting-started/git-sync.md
  getting-started/git-sync/bi-directional-git-integration: getting-started/git-sync.md
  getting-started/git-sync/enabling-github-sync: getting-started/git-sync/enabling-github-sync.md
  getting-started/git-sync/enabling-gitlab-sync: getting-started/git-sync/enabling-gitlab-sync.md
  getting-started/git-sync/content-configuration: getting-started/git-sync/content-configuration.md
  getting-started/git-sync/github-pull-request-preview: getting-started/git-sync/github-pull-request-preview.md
  getting-started/git-sync/commits: getting-started/git-sync/commits.md
  getting-started/git-sync/monorepos: getting-started/git-sync/monorepos.md
  getting-started/git-sync/troubleshooting: getting-started/git-sync/troubleshooting.md
  getting-started/content-structure: creating-content/content-structure.md
  getting-started/content-structure/what-is-a-space: creating-content/content-structure/space.md
  getting-started/content-structure/content-structure: creating-content/content-structure/page.md
  getting-started/content-structure/what-is-a-collection: creating-content/content-structure/collection.md
  getting-started/collaboration: collaboration/live-edits.md
  getting-started/collaboration/live-edits: collaboration/live-edits.md
  getting-started/collaboration/change-requests: collaboration/change-requests.md
  getting-started/collaboration/comments-discussion: collaboration/comments.md
  getting-started/publishing: publishing-documentation/publish-a-docs-site.md
  getting-started/publishing/space-publishing: publishing-documentation/publish-a-docs-site.md
  getting-started/publishing/collection-publishing: publishing-documentation/publish-a-docs-site.md
  getting-started/publishing/share-links: publishing-documentation/publish-a-docs-site/share-links.md
  features/import: getting-started/import.md
  content-editor/editing-content/rich-text: creating-content/formatting.md
  content-editor/searching-your-content/lens: creating-content/searching-your-content/gitbook-ai.md
  content-editor/overview: creating-content/formatting.md
  content-editor/import: getting-started/import.md
  content-editor/editor: creating-content/formatting.md
  content-editor/editor/navigation: resources/gitbook-ui.md
  content-editor/editor/content-structure: creating-content/content-structure.md
  content-editor/editor/content-structure/what-is-a-space: creating-content/content-structure/space.md
  content-editor/editor/content-structure/content-in-a-space: creating-content/content-structure/page.md
  content-editor/editor/content-structure/what-is-a-collection: creating-content/content-structure/collection.md
  content-editor/editing-content: creating-content/formatting.md
  content-editor/editing-content/live-edits: collaboration/live-edits.md
  content-editor/editing-content/formatting: creating-content/formatting.md
  content-editor/editing-content/inline: creating-content/formatting/inline.md
  content-editor/editing-content/markdown: creating-content/formatting/markdown.md
  content-editor/editing-content/write-and-edit-with-ai: creating-content/write-and-edit-with-ai.md
  content-editor/blocks: creating-content/blocks.md
  content-editor/blocks/paragraph: creating-content/blocks/paragraph.md
  content-editor/blocks/heading: creating-content/blocks/heading.md
  content-editor/blocks/unordered-list: creating-content/blocks/unordered-list.md
  content-editor/blocks/ordered-list: creating-content/blocks/ordered-list.md
  content-editor/blocks/task-list: creating-content/blocks/task-list.md
  content-editor/blocks/hint: creating-content/blocks/hint.md
  content-editor/blocks/quote: creating-content/blocks/quote.md
  content-editor/blocks/code-block: creating-content/blocks/code-block.md
  content-editor/blocks/insert-files: creating-content/blocks/insert-files.md
  content-editor/blocks/insert-images: creating-content/blocks/insert-images.md
  content-editor/blocks/embed-a-url: creating-content/blocks/embed-a-url.md
  content-editor/blocks/table: creating-content/blocks/table.md
  content-editor/blocks/cards: creating-content/blocks/cards.md
  content-editor/blocks/tabs: creating-content/blocks/tabs.md
  content-editor/blocks/expandable: creating-content/blocks/expandable.md
  content-editor/blocks/stepper: creating-content/blocks/stepper.md
  content-editor/blocks/drawing: creating-content/blocks/drawing.md
  content-editor/blocks/math-and-tex: creating-content/blocks/math-and-tex.md
  content-editor/blocks/openapi: creating-content/openapi.md
  content-editor/blocks/openapi/support-for-ci-cd-with-api-blocks: creating-content/openapi/support-for-ci-cd-with-api-blocks.md
  content-editor/blocks/page-link: creating-content/blocks/page-link.md
  content-editor/blocks/reusable-content-blocks-beta: creating-content/reusable-content.md
  content-editor/broken-links: creating-content/broken-links.md
  content-editor/searching-your-content: creating-content/searching-your-content.md
  content-editor/searching-your-content/gitbook-ai: creating-content/searching-your-content/gitbook-ai.md
  content-editor/searching-your-content/quick-find: creating-content/searching-your-content/quick-find.md
  content-editor/activity-history: creating-content/version-control.md
  reusable-content/overview: creating-content/reusable-content.md
  published-documentation/overview: publishing-documentation/publish-a-docs-site.md
  published-documentation/publish-a-docs-site: publishing-documentation/publish-a-docs-site.md
  published-documentation/publish-a-docs-site/public-publishing: publishing-documentation/publish-a-docs-site/public-publishing.md
  published-documentation/publish-a-docs-site/share-links: publishing-documentation/publish-a-docs-site/share-links.md
  published-documentation/publish-a-docs-site/visitor-authentication: publishing-documentation/visitor-authentication.md
  published-documentation/site-structure-and-navigation: publishing-documentation/site-structure.md
  published-documentation/site-structure-and-navigation/publish-multiple-spaces-on-one-site: publishing-documentation/site-structure/variants.md
  published-documentation/site-structure-and-navigation/site-sections: publishing-documentation/site-structure/site-sections.md
  published-documentation/customization: publishing-documentation/customization.md
  published-documentation/customization/page-layouts: creating-content/content-structure/page.md.md
  published-documentation/customization/space-customization: publishing-documentation/customization.md
  published-documentation/customization/collection-customization: publishing-documentation/customization.md
  published-documentation/custom-domain: publishing-documentation/custom-domain.md
  published-documentation/custom-domain/choose: publishing-documentation/custom-domain.md
  published-documentation/custom-domain/organization-level-custom-domain: publishing-documentation/custom-domain.md
  published-documentation/custom-domain/configure-dns: publishing-documentation/custom-domain.md
  published-documentation/custom-domain/finalize: publishing-documentation/custom-domain.md
  published-documentation/custom-domain/troubleshooting: publishing-documentation/custom-domain.md
  published-documentation/insights: publishing-documentation/insights.md
  published-documentation/site-settings: publishing-documentation/site-settings.md
  published-documentation/site-redirects: publishing-documentation/site-redirects.md
  published-documentation/site-permissions: publishing-documentation/publish-a-docs-site.md
  publishing-documentation/customization/collection-customization: publishing-documentation/customization.md
  publishing-documentation/customization/space-customization: publishing-documentation/customization.md
  collaboration/share/space-publishing: collaboration/share.md
  collaboration/share/collection-publishing: collaboration/share.md
  collaboration/collaboration: collaboration/share.md
  collaboration/change-requests: collaboration/change-requests.md
  collaboration/share/share-a-space: collaboration/share.md
  collaboration/share/share-a-collection: collaboration/share.md
  collaboration/share/pdf-export: collaboration/pdf-export.md
  collaboration/comments-discussion: collaboration/comments.md
  tour/quick-find: creating-content/searching-your-content/quick-find.md
  tour/editor: creating-content/formatting.md
  tour/editor/rich-text: creating-content/formatting.md
  tour/editor/blocks: creating-content/blocks.md
  tour/editor/blocks/paragraph: creating-content/blocks/paragraph.md
  tour/editor/blocks/cards: creating-content/blocks/cards.md
  tour/editor/blocks/heading: creating-content/blocks/heading.md
  tour/editor/blocks/unordered-list: creating-content/blocks/unordered-list.md
  tour/editor/blocks/ordered-list: creating-content/blocks/ordered-list.md
  tour/editor/blocks/task-list: creating-content/blocks/task-list.md
  tour/editor/blocks/hint: creating-content/blocks/hint.md
  tour/editor/blocks/quote: creating-content/blocks/quote.md
  tour/editor/blocks/code-block: creating-content/blocks/code-block.md
  tour/editor/blocks/insert-files: creating-content/blocks/insert-files.md
  tour/editor/blocks/insert-images: creating-content/blocks/insert-images.md
  tour/editor/blocks/embed-a-url: creating-content/blocks/embed-a-url.md
  tour/editor/blocks/table: creating-content/blocks/table.md
  tour/editor/blocks/tabs: creating-content/blocks/tabs.md
  tour/editor/blocks/expandable: creating-content/blocks/expandable.md
  tour/editor/blocks/drawing: creating-content/blocks/drawing.md
  tour/editor/blocks/math-and-tex: creating-content/blocks/math-and-tex.md
  tour/editor/blocks/api-method: creating-content/blocks/api-method.md
  tour/editor/blocks/openapi: creating-content/openapi.md
  tour/editor/blocks/page-link: creating-content/blocks/page-link.md
  tour/editor/inline: creating-content/formatting/inline.md
  tour/editor/inline/image: creating-content/formatting/inline.md
  tour/editor/inline/emoji: creating-content/formatting/inline.md
  tour/editor/inline/link: creating-content/formatting/inline.md
  tour/editor/inline/math-and-tex: creating-content/formatting/inline.md
  tour/editor/formatting: creating-content/formatting.md
  tour/editor/markdown: creating-content/formatting/markdown.md
  tour/customization: publishing-documentation/customization.md
  tour/customization/space-customization: publishing-documentation/customization.md
  tour/customization/collection-customization: publishing-documentation/customization.md
  tour/member-management: account-management/member-management.md
  tour/member-management/invite-members-to-your-organization: account-management/member-management/invite-members-to-your-organization.md
  tour/member-management/roles: account-management/member-management/roles.md
  tour/member-management/teams: account-management/member-management/teams.md
  tour/member-management/permissions-and-inheritance: account-management/member-management/permissions-and-inheritance.md
  tour/pdf-export: collaboration/pdf-export.md
  tour/activity-history: creating-content/version-control.md
  tour/insights: publishing-documentation/insights.md
  tour/notifications: collaboration/notifications.md
  tour/internationalization: publishing-documentation/site-structure/variants.md
  tour/keyboard-shortcuts: resources/keyboard-shortcuts.md
  resources/keyboard-shortcuts: resources/keyboard-shortcuts.md
  product-tour/keyboard-shortcuts: resources/keyboard-shortcuts.md
  advanced-guides/custom-domain: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/choose: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/location: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/initiate: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/initiate/organization-level-custom-domain: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/initiate/collection-level-custom-domain: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/initiate/space-level-custom-domain: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/configure-dns: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/finalize: publishing-documentation/custom-domain.md
  advanced-guides/custom-domain/troubleshooting: publishing-documentation/custom-domain.md
  advanced-guides/advanced-sharing-and-security: account-management/sso-and-saml.md
  advanced-guides/advanced-sharing-and-security/sso-and-saml: account-management/sso-and-saml.md
  advanced-guides/advanced-sharing-and-security/saml: account-management/sso-and-saml.md
  advanced-guides/advanced-sharing-and-security/scim-and-directory-sync: account-management/sso-and-saml.md
  advanced-guides/advanced-sharing-and-security/visitor-authentication: publishing-documentation/visitor-authentication.md
  advanced-guides/integrations: integrations/install-an-integration.md
  advanced-guides/integrations/integrations-faq: integrations/install-an-integration.md
  advanced-guides/integrations/install-an-integration: integrations/install-an-integration.md
  advanced-guides/integrations/arcade: integrations/install-an-integration.md
  advanced-guides/integrations/arcade/configure-the-arcade-integration: integrations/install-an-integration.md
  advanced-guides/integrations/fathom: integrations/install-an-integration.md
  advanced-guides/integrations/fathom/configure-the-fathom-integration: integrations/install-an-integration.md
  advanced-guides/integrations/figma: integrations/install-an-integration.md
  advanced-guides/integrations/figma/configure-the-figma-integration: integrations/install-an-integration.md
  advanced-guides/integrations/google-analytics: integrations/install-an-integration.md
  advanced-guides/integrations/google-analytics/configure-the-google-analytics-integration: integrations/install-an-integration.md
  advanced-guides/integrations/intercom: integrations/install-an-integration.md
  advanced-guides/integrations/inter: integrations/install-an-integration.md
  advanced-guides/integrations/jira: integrations/install-an-integration.md
  advanced-guides/integrations/jira/configure-the-jira-integration: integrations/install-an-integration.md
  advanced-guides/integrations/linear: integrations/install-an-integration.md
  advanced-guides/integrations/linear/configure-the-integration: integrations/install-an-integration.md
  advanced-guides/integrations/mailchimp: integrations/install-an-integration.md
  advanced-guides/integrations/mailchimp/configure-the-mailchimp-integration: integrations/install-an-integration.md
  advanced-guides/integrations/mermaid: integrations/install-an-integration.md
  advanced-guides/integrations/mermaid/configure-the-mermaid-integration: integrations/install-an-integration.md
  advanced-guides/integrations/plausible: integrations/install-an-integration.md
  advanced-guides/integrations/plausible/configure-the-plausible-integration: integrations/install-an-integration.md
  advanced-guides/integrations/runkit: integrations/install-an-integration.md
  advanced-guides/integrations/runkit/configure-the-runkit-integration: integrations/install-an-integration.md
  advanced-guides/integrations/segment: integrations/install-an-integration.md
  advanced-guides/integrations/segment/configure-the-integration: integrations/install-an-integration.md
  advanced-guides/integrations/segment/gitbook-segment-event: integrations/install-an-integration.md
  advanced-guides/integrations/sentry: integrations/install-an-integration.md
  advanced-guides/integrations/sentry/configure-the-sentry-integration: integrations/install-an-integration.md
  advanced-guides/integrations/slack: integrations/install-an-integration.md
  advanced-guides/integrations/slack/configure-the-slack-integration: integrations/install-an-integration.md
  integrations/overview: integrations/install-an-integration.md
  integrations/git-sync: getting-started/git-sync.md
  integrations/git-sync/enabling-github-sync: getting-started/git-sync/enabling-github-sync.md
  integrations/git-sync/enabling-gitlab-sync: getting-started/git-sync/enabling-gitlab-sync.md
  integrations/git-sync/content-configuration: getting-started/git-sync/content-configuration.md
  integrations/git-sync/commits: getting-started/git-sync/commits.md
  integrations/git-sync/monorepos: getting-started/git-sync/monorepos.md
  integrations/git-sync/troubleshooting: getting-started/git-sync/troubleshooting.md
  integrations/third-party-integrations: integrations/install-an-integration.md
  integrations/integrations-faq: integrations/install-an-integration.md
  integrations/git-sync/github-pull-request-preview: getting-started/git-sync/github-pull-request-preview.md
  billing-and-admin/account-settings: account-management/account-settings.md
  billing-and-admin/plans: account-management/plans/README.md
  billing-and-admin/plans/organization-management: account-management/organization-settings.md
  billing-and-admin/plans/free-trial: account-management/plans.md
  billing-and-admin/plans/non-profit-open-source-plan: account-management/plans/apply-for-the-non-profit-open-source-plan.md
  billing-and-admin/plans/billing-policy: account-management/plans/billing-policy.md
  billing-and-admin/plans/cancelling-a-plan: account-management/cancelling-a-plan.md
  account-management/overview: account-management/plans.md
  account-management/organization-management: account-management/organization-settings.md
  account-management/sso-and-saml/sso-and-saml: account-management/sso-and-saml.md
  account-management/sso-and-saml/saml/sso-members-vs-non-sso: account-management/sso-and-saml/sso-members-vs-non-sso.md
  help-and-faq/keyboard-shortcuts: resources/keyboard-shortcuts.md
  snippets-and-content-insights/overview: snippets-and-insights/overview.md
  snippets-and-content-insights/snippets: snippets-and-insights/snippets-beta.md
  snippets-and-content-insights/snippets-beta: snippets-and-insights/snippets-beta.md
  snippets-and-content-insights/insights: snippets-and-insights/insights.md
