redirects:
	tour/quick-find: product-tour/quick-find.md
	tour/insights: publishing/insights.md
	tour/keyboard-shortcuts: product-tour/keyboard-shortcuts.md
	tour/seo: publishing/seo.md
	advanced-guides/advanced-sharing-and-security: product-tour/sso-and-saml.md
	advanced-guides/advanced-sharing-and-security/sso-and-saml: product-tour/sso-and-saml.md
	advanced-guides/advanced-sharing-and-security/saml: product-tour/sso-and-saml/saml
	advanced-guides/advanced-sharing-and-security/scim-and-directory-sync: product-tour/sso-and-saml/scim-and-directory-sync.md
	advanced-guides/integrations: product-tour/integrations.md
	advanced-guides/integrations/integrations-faq: product-tour/integrations/integrations-faq.md
	advanced-guides/integrations/install-an-integration: product-tour/integrations/install-an-integration.md
	advanced-guides/integrations/arcade: product-tour/integrations/arcade.md
	advanced-guides/integrations/arcade/configure-the-arcade-integration: product-tour/integrations/arcade/configure.md
	advanced-guides/integrations/fathom: product-tour/integrations/fathom.md
	advanced-guides/integrations/fathom/configure-the-fathom-integration: product-tour/integrations/fathom/configure.md
	advanced-guides/integrations/figma: product-tour/integrations/figma.md
	advanced-guides/integrations/figma/configure-the-figma-integration: product-tour/integrations/figma/configure.md
	advanced-guides/integrations/google-analytics: product-tour/integrations/google-analytics.md
	advanced-guides/integrations/google-analytics/configure-the-google-analytics-integration: product-tour/integrations/google-analytics/configure.md
	advanced-guides/integrations/intercom: product-tour/integrations/intercom.md
	advanced-guides/integrations/intercom/configure-the-intercom-integration: product-tour/integrations/intercom/configure.md
	advanced-guides/integrations/jira: product-tour/integrations/jira.md
	advanced-guides/integrations/jira/configure-the-jira-integration: product-tour/integrations/jira/configure.md
	advanced-guides/integrations/linear: product-tour/integrations/linear.md
	advanced-guides/integrations/linear/configure-the-integration: product-tour/integrations/linear/configure.md
	advanced-guides/integrations/mailchimp: product-tour/integrations/mailchimp.md
	advanced-guides/integrations/mailchimp/configure-the-mailchimp-integration: product-tour/integrations/mailchimp/configure.md
	advanced-guides/integrations/mermaid: product-tour/integrations/mermaid.md
	advanced-guides/integrations/mermaid/configure-the-mermaid-integration: product-tour/integrations/mermaid/configure.md
	advanced-guides/integrations/plausible: product-tour/integrations/plausible.md
	advanced-guides/integrations/plausible/configure-the-plausible-integration: product-tour/integrations/plausible/configure.md
	advanced-guides/integrations/runkit: product-tour/integrations/runkit.md
	advanced-guides/integrations/runkit/configure-the-runkit-integration: product-tour/integrations/runkit/configure.md
	advanced-guides/integrations/segment: product-tour/integrations/segment.md
	advanced-guides/integrations/segment/configure-the-integration: product-tour/integrations/segment/configure.md
	advanced-guides/integrations/segment/gitbook-segment-event: product-tour/integrations/segment/event.md
	advanced-guides/integrations/sentry: product-tour/integrations/sentry.md
	advanced-guides/integrations/sentry/configure-the-sentry-integration: product-tour/integrations/sentry/configure.md
	advanced-guides/integrations/slack: product-tour/integrations/slack.md
	advanced-guides/integrations/slack/configure-the-slack-integration: product-tour/integrations/slack/configure.md
	billing-and-admin/plans/free-trial: account-management/plans.md
